---
name: Tests
on:
  push:
    branches: [master]
  pull_request:

# Start with explicit read-only permissions.
permissions:
  contents: read


# Cancel pending jobs if a new commit was pushed for the same branch.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true


jobs:
  tests:
    runs-on: ${{ matrix.os-version }}
    strategy:
      fail-fast: false
      matrix:
        os-version:
          - ubuntu-latest
          - windows-latest
          - macos-latest
        python-version:
          - '3.9'
          - '3.10'
          - '3.11'
          - '3.12'
          - '3.13'

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install -r requirements_dev.txt

      - name: Install project
        run: |
          python -m pip install -e .


      - name: Run all tests for ${{ matrix.python-version }}
        run: |
          python -m pytest
